name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: 'Types'
    labels:
      - 'types'
  - title: 'Documentation'
    labels:
      - 'documentation'
  - title: '🧰 Maintenance'
    labels: 
      - 'chore'
      - 'dependencies'
      - 'performance'
      - 'refactoring'
exclude-labels:
  - 'infrastructure'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&`#@'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  # Essential Links

  * [npm](https://www.npmjs.com/package/chartjs-chart-treemap)
  * [Docs](https://chartjs-chart-treemap.pages.dev/)
  * [Samples](https://chartjs-chart-treemap.pages.dev/samples/basic.html)

  $CHANGES
